import { SubTaskDto } from '../src/domain/useCases/SubtTaskDto';
import { TaskDto } from '../src/domain/useCases/TaskDto';
import { CreateSubTaskUseCase } from '../src/domain/useCases/subTasks/CreateSubTaskUseCase';
import { DeleteSubTaskUseCase } from '../src/domain/useCases/subTasks/DeleteSubTaskUseCase';
import { CreateTaskUseCase } from '../src/domain/useCases/tasks/CreateTaskUseCase';
import { DeleteTaskUseCase } from '../src/domain/useCases/tasks/DeleteTaskUseCase';
import { GetAllTasksUseCase } from '../src/domain/useCases/tasks/GetAllTasksUseCase';
import { GetTaskUseCase } from '../src/domain/useCases/tasks/GetTaskUseCase';
import { UpdateTaskUseCase } from '../src/domain/useCases/tasks/UpdateTaskUseCase';
import { SubTasksController } from '../src/presentation/controllers/subTasksController';
import { TasksController } from '../src/presentation/controllers/tasksController';
import { TodoRouter } from '../src/presentation/routes/todo-router';

const autoGeneratedTime = new Date();
const newTitle = { title: 'new title' };
export const mockTask = {
  title: 'Test Task',
  description: 'Test Description',
  completed: false,
  createdAt: autoGeneratedTime,
  updatedAt: autoGeneratedTime,
  subTasks: [],
};

export const mockSubTask: SubTaskDto = {
  title: 'SubTask Title',
};

export const normalisedMockTask = {
  ...mockTask,
  ...{
    createdAt: autoGeneratedTime.toISOString(),
    updatedAt: autoGeneratedTime.toISOString(),
  },
};

export class GetAllTasksUseCaseMock {
  async execute(): Promise<TaskDto[]> {
    return [mockTask];
  }
}

export class GetTaskUseCaseMock {
  async execute(): Promise<TaskDto> {
    return mockTask;
  }
}

export class CreateTaskUseCaseMock {
  async execute(): Promise<TaskDto> {
    return mockTask;
  }
}

export class UpdateTaskUseCaseMock {
  async execute(): Promise<TaskDto> {
    return { ...mockTask, ...newTitle };
  }
}

export class DeleteTaskUseCaseMock {
  async execute(): Promise<TaskDto[]> {
    return [];
  }
}

export class CreateSubTaskUseCaseMock {
  async execute(): Promise<SubTaskDto[]> {
    return [mockSubTask];
  }
}

export class DeleteSubTaskUseCaseMock {
  async execute(): Promise<{ deleted: boolean }> {
    return { deleted: true };
  }
}

const tasksController = new TasksController(
  new GetAllTasksUseCaseMock() as GetAllTasksUseCase,
  new GetTaskUseCaseMock() as unknown as GetTaskUseCase,
  new CreateTaskUseCaseMock() as unknown as CreateTaskUseCase,
  new UpdateTaskUseCaseMock() as unknown as UpdateTaskUseCase,
  new DeleteTaskUseCaseMock() as unknown as DeleteTaskUseCase,
);
const subTasksController = new SubTasksController(
  new CreateSubTaskUseCaseMock() as unknown as CreateSubTaskUseCase,
  new DeleteSubTaskUseCaseMock() as unknown as DeleteSubTaskUseCase,
);

export const router = new TodoRouter(tasksController, subTasksController);
